#!/bin/bash

# Curupira CLI Wrapper
# Generated by install.sh

PROJECT_DIR="__PROJECT_DIR__"
USER_NAME="__USER_NAME__"
VENV_PYTHON="$PROJECT_DIR/venv/bin/python"
BOT_SCRIPT="$PROJECT_DIR/bot.py"
SERVICE_NAME="curupira"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

function show_help {
    echo -e "${GREEN}Curupira BOT - Comandos:${NC}"
    echo "  acorda, wakeup      -> Roda o bot agora (foreground)"
    echo "  daemon              -> Instala e inicia como serviço do sistema (boot automático)"
    echo "  parar, stop         -> Para o serviço do sistema"
    echo "  reiniciar, restart  -> Reinicia o serviço do sistema"
    echo "  logs                -> Vê os logs do serviço (journalctl)"
    echo "  status              -> Vê status do serviço"
}

function run_wakeup {
    echo -e "${YELLOW}Acordando o Curupira...${NC}"
    cd "$PROJECT_DIR"
    exec "$VENV_PYTHON" "$BOT_SCRIPT"
}

function install_daemon {
    echo -e "${BLUE}Configurando serviço systemd (Daemon)...${NC}"
    
    # Check sudo
    if [ "$EUID" -ne 0 ]; then 
        echo -e "${RED}Por favor, rode o comando daemon com sudo:${NC}"
        echo "sudo curupira daemon"
        exit 1
    fi

    SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"

    cat <<EOF > "$SERVICE_FILE"
[Unit]
Description=Curupira BOT Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER_NAME
WorkingDirectory=$PROJECT_DIR
ExecStart=$VENV_PYTHON $BOT_SCRIPT
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable $SERVICE_NAME
    systemctl start $SERVICE_NAME
    
    echo -e "${GREEN}Serviço instalado e iniciado!${NC}"
    echo "Use 'curupira logs' para ver a saída."
}

function stop_service {
    echo "Parando serviço..."
    sudo systemctl stop $SERVICE_NAME
}

function restart_service {
    echo "Reiniciando serviço..."
    sudo systemctl restart $SERVICE_NAME
}

function show_logs {
    journalctl -u $SERVICE_NAME -f
}

function show_status {
    systemctl status $SERVICE_NAME
}

case "$1" in
    acorda|wakeup)
        run_wakeup
        ;;
    daemon)
        install_daemon
        ;;
    parar|stop)
        stop_service
        ;;
    reiniciar|restart)
        restart_service
        ;;
    logs)
        show_logs
        ;;
    status)
        show_status
        ;;
    *)
        show_help
        ;;
esac
